### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Douglasj02**

### CODE REVIEW

**Review by zionvanwyk — APPROVED** [review]
demo 2, here we come!

**Review by MariePretorius — APPROVED** [review]
awesome!

**Review by 21434809 — APPROVED** [review]
Looks good .only see Spotify keys has issues it that fine ?

**Comment by Douglasj02** [comment]
> Looks good .only see Spotify keys has issues it that fine ?

I think it picks it up from a previous commit in the clustering but it's been changed now

**Review by Divergent-Caesar — APPROVED** [review]
Some dodgy stuff happening but we'll figure it out

**Comment by Douglasj02** [comment]
> > Looks good .only see Spotify keys has issues it that fine ?
> 
> I think it picks it up from a previous commit in the clustering but it's been changed now

Fixed now by changing the secrets

**Pull request merged**
